<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project basedir="." default="package" name="chlasm">
    <property name="debuglevel" value="source,lines,vars"/>
    <property name="target" value="11"/>
    <property name="source" value="11"/>
	
    <path id="chlasm.classpath">
        <pathelement location="bin"/>
    </path>
    
    <target name="init">
        <mkdir dir="bin"/>
    	<mkdir dir="build"/>
        <copy includeemptydirs="false" todir="bin">
            <fileset dir="src">
                <exclude name="**/*.launch"/>
                <exclude name="**/*.xtend"/>
                <exclude name="**/*.java"/>
            </fileset>
        </copy>
    </target>
	
    <target name="clean">
        <delete dir="bin"/>
    	<delete dir="build"/>
    </target>
	
    <target name="cleanall" depends="clean"/>
	
    <target name="build-project" depends="init">
        <echo message="${ant.project.name}: ${ant.file}"/>
        <javac debug="true" debuglevel="${debuglevel}" destdir="bin" includeantruntime="false" source="${source}" target="${target}">
            <src path="src"/>
            <classpath refid="chlasm.classpath"/>
        </javac>
    </target>
	
	<target name="build-subprojects"></target>
	
	<target name="build" depends="build-subprojects,build-project"/>
    
	<target name="build-refprojects" description="Build all projects which reference this project."/>
    
  	<target name="jar" description="Create JAR" depends="clean, build">
  	    <jar destfile="build/chlasm.jar" basedir="bin">
  	    	<fileset dir="bin">
  	    		<include name="**/*.class"/>
  	    	</fileset>
  	    	<fileset dir=".">
  	    		<include name="COPYING.TXT"/>
  	    		<include name="README.TXT"/>
  	    	</fileset>
  	    </jar>
  	</target>
	
	<target name="package" description="Package JAR, CMD, license and samples" depends="jar">
	  	<mkdir dir="build/chlasm"/>
		<mkdir dir="build/chlasm/headers"/>
		<mkdir dir="build/chlasm/samples/bw1_story"/>
		<mkdir dir="build/chlasm/samples/sample1"/>
		<mkdir dir="build/chlasm/samples/sample2"/>
		
		<copy includeemptydirs="false" todir="build/chlasm">
			<fileset dir="build">
                <include name="chlasm.jar"/>
            </fileset>
			<fileset dir=".">
            	<include name="chlasm.cmd"/>
	  			<include name="COPYING.TXT"/>
  	    		<include name="README.TXT"/>
            </fileset>
        </copy>
		
		<copy includeemptydirs="false" todir="build/chlasm/headers">
			<fileset dir="headers">
                <include name="*"/>
            </fileset>
        </copy>
		
		<copy includeemptydirs="false" todir="build/chlasm/samples/bw1_story">
			<fileset dir="samples/bw1_story">
                <include name="_project.txt"/>
            </fileset>
        </copy>
		
		<copy includeemptydirs="false" todir="build/chlasm/samples/sample1">
			<fileset dir="samples/sample1">
                <include name="*"/>
            </fileset>
        </copy>
		
		<copy includeemptydirs="false" todir="build/chlasm/samples/sample2">
			<fileset dir="samples/sample2">
                <include name="*"/>
            </fileset>
        </copy>
		
		<zip destfile="build/chlasm.zip">
	  		<fileset dir="build">
	  			<include name="chlasm/**"/>
	  		</fileset>
	  	</zip>
	</target>
	
	<target name="bw1_story" description="Compile original story">
		<condition property="chlasm.missing">
			<not>
		    	<available file="build/chlasm.jar"/>
			</not>
		</condition>
		<fail if="chlasm.missing" message="File build/chlasm.jar not found"/>
		
		<delete file="samples/bw1_story/_challenge.chl"/>
		
        <java fork="true" dir="samples/bw1_story" classpath="build/chlasm.jar" classname="it.ld.bw.chl.Main"
        	args="-compile -p _project.txt -o _challenge.chl -noshr -jst"/>
    </target>
	
	<target name="validate" description="Build JAR, compile BW1 story and compare output with original chl" depends="jar">
		<delete dir="samples/bw1_story/bin"/>
		
		<antcall target="bw1_story"/>
		
		<java fork="true" dir="samples/bw1_story" classpath="build/chlasm.jar" classname="it.ld.bw.chl.Main"
		        	args="-cmp -f1 _original.chl -f2 _challenge.chl -strict"/>
	</target>
</project>
